theme: jekyll-theme-cayman
title: Dylan "Dyl-M" Monfret
description: Personal website hosted by GitHub Pages to present my projects, researches and thoughts about machine 
    learning, development (mainly Python) and other IT issues.
